// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {updater} from '../models';

export function AlignBlocks(arg1:string,arg2:Array<string>):Promise<Array<types.BoundingBox>>;

export function CheckForUpdates():Promise<updater.UpdateCheckResult>;

export function CheckInvoiceMath(arg1:string):Promise<types.InvoiceValidationResult>;

export function ExtractText(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GenerateBugReport(arg1:string,arg2:string):Promise<string>;

export function GetClipboardImage():Promise<types.QueueItem>;

export function GetConfig():Promise<types.Config>;

export function GetUsageStats():Promise<types.UsageStats>;

export function LoadHistory():Promise<Array<types.QueueItem>>;

export function PickFiles():Promise<Array<types.QueueItem>>;

export function SaveConfig(arg1:types.Config):Promise<void>;

export function SaveExportFile(arg1:string,arg2:string):Promise<string>;

export function SaveHistory(arg1:Array<types.QueueItem>):Promise<void>;

export function ScanDocument():Promise<types.QueueItem>;

export function TransformText(arg1:string,arg2:string):Promise<string>;
