// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AlignBlocks(arg1, arg2) {
  return window['go']['main']['App']['AlignBlocks'](arg1, arg2);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CheckInvoiceMath(arg1) {
  return window['go']['main']['App']['CheckInvoiceMath'](arg1);
}

export function ExtractText(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExtractText'](arg1, arg2, arg3);
}

export function GenerateBugReport(arg1, arg2) {
  return window['go']['main']['App']['GenerateBugReport'](arg1, arg2);
}

export function GetClipboardImage() {
  return window['go']['main']['App']['GetClipboardImage']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetUsageStats() {
  return window['go']['main']['App']['GetUsageStats']();
}

export function LoadHistory() {
  return window['go']['main']['App']['LoadHistory']();
}

export function PickFiles() {
  return window['go']['main']['App']['PickFiles']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveExportFile(arg1, arg2) {
  return window['go']['main']['App']['SaveExportFile'](arg1, arg2);
}

export function SaveHistory(arg1) {
  return window['go']['main']['App']['SaveHistory'](arg1);
}

export function ScanDocument() {
  return window['go']['main']['App']['ScanDocument']();
}

export function TransformText(arg1, arg2) {
  return window['go']['main']['App']['TransformText'](arg1, arg2);
}
