// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

const getApp = () => {
  if (typeof window !== 'undefined' && window['go'] && window['go']['main'] && window['go']['main']['App']) {
    return window['go']['main']['App'];
  }
  return null;
};

export function GetConfig() {
  const app = getApp();
  if (app && app.GetConfig) return app.GetConfig();
  return Promise.resolve({
    session_account: 'default_user',
    api_key: '',
    base_url: 'https://api.openai.com/v1',
    model_name: 'gpt-4o-mini',
    auto_extract: true,
    default_output_mode: 'document',
    quality: 'standard',
    releases_repo: 'its-Sohan/itt-ocr-release',
    check_updates_on_startup: true,
    usage_stats: {
      total_scanned_or_uploaded: 0,
      total_processed: 0,
      total_characters_extracted: 0,
      successful_runs: 0,
      failed_runs: 0,
    },
  });
}

export function SaveConfig(arg1) {
  const app = getApp();
  if (app && app.SaveConfig) return app.SaveConfig(arg1);
  return Promise.resolve();
}

export function GetUsageStats() {
  const app = getApp();
  if (app && app.GetUsageStats) return app.GetUsageStats();
  return Promise.resolve({
    total_scanned_or_uploaded: 0,
    total_processed: 0,
    total_characters_extracted: 0,
    successful_runs: 0,
    failed_runs: 0,
  });
}

export function LoadHistory() {
  const app = getApp();
  if (app && app.LoadHistory) return app.LoadHistory();
  return Promise.resolve([]);
}

export function SaveHistory(arg1) {
  const app = getApp();
  if (app && app.SaveHistory) return app.SaveHistory(arg1);
  return Promise.resolve();
}

export function PickFiles() {
  const app = getApp();
  if (app && app.PickFiles) return app.PickFiles();
  return Promise.resolve([]);
}

export function GetClipboardImage() {
  const app = getApp();
  if (app && app.GetClipboardImage) return app.GetClipboardImage();
  return Promise.reject(new Error('Clipboard image extraction requires native desktop environment.'));
}

export function ScanDocument() {
  const app = getApp();
  if (app && app.ScanDocument) return app.ScanDocument();
  return Promise.reject(new Error('Hardware scanning requires native desktop environment.'));
}

export function ExtractText(filePath, mode, quality) {
  const app = getApp();
  if (app && app.ExtractText) return app.ExtractText(filePath, mode, quality);
  return Promise.resolve("Sample extracted text in browser preview mode.");
}

export function AlignBlocks(filePath, blocks) {
  const app = getApp();
  if (app && app.AlignBlocks) return app.AlignBlocks(filePath, blocks);
  return Promise.resolve([]);
}

export function TransformText(text, transformType) {
  const app = getApp();
  if (app && app.TransformText) return app.TransformText(text, transformType);
  return Promise.resolve(text);
}

export function CheckInvoiceMath(text) {
  const app = getApp();
  if (app && app.CheckInvoiceMath) return app.CheckInvoiceMath(text);
  return Promise.resolve(null);
}

export function SaveExportFile(defaultFilename, content) {
  const app = getApp();
  if (app && app.SaveExportFile) return app.SaveExportFile(defaultFilename, content);
  return Promise.resolve("");
}

export function CheckForUpdates() {
  const app = getApp();
  if (app && app.CheckForUpdates) return app.CheckForUpdates();
  return Promise.resolve({
    has_update: false,
    current_version: '1.0.0',
    latest_version: '1.0.0',
    release_notes: '',
    release_url: '',
    download_url: '',
  });
}

export function GenerateBugReport(description, steps) {
  const app = getApp();
  if (app && app.GenerateBugReport) return app.GenerateBugReport(description, steps);
  return Promise.resolve("/tmp/sample_bug_report.json");
}
